config/routes.rb
Rails.application.routes.draw do
  devise_for :user, :skip => [:sessions, :registrations]
  devise_scope :user do
    get "/login" => "devise/sessions#new", as: :new_user_session
    post "/login" => "sessions#create", as: :user_session
    delete "/logout" => "devise/sessions#destroy", as: :destroy_user_session
    get "/sign_up" => "devise/registrations#new", as: :new_user_registration
    post "/sign_up" => "registrations#create", as: :user_registration
  end

  resources :posts
  resources :user_followings, only: [:create, :destroy]
  resources :comments

  get '/users' => 'users#index', as: :users
  get '/users/:id' => 'users#show', as: :user
  root 'users#dashboard'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true
  belongs_to :user

  default_scope -> { order('created_at ASC') }

  validates :user, presence: true
  validates :commentable, presence: true
  validates :comment, presence: true

  #censorable :comment
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    authorize! :create, Comment
    commentable = Post.find(params[:comment][:commentable_id])
    comment = Comment.new(params[:comment].permit(:comment, :commentable_id, :commentable_type).merge({user_id: current_user.id}))
    status = comment.save
    render json: { comment: status ? render_to_string(partial: 'comments/comment', locals: { comment: comment }) : '',
                   form: render_to_string(partial: 'comments/form', locals: { post: commentable,
                                                                              comment: status ? Comment.new(commentable: commentable) : comment }) },
           status: status ? :ok : :unprocessable_entity
  end

  def destroy
    comment = Comment.find(params[:id])
    authorize! :destroy, comment
    status = comment.destroy
    render json: {}, status: status ? :ok : :unprocessable_entity
  end
end

app/views/comments/_comment.erb
<div class="panel panel-default comment">
  <div class="panel-heading">
    <span class="bold"><%= comment.user.email %></span> commented:
  </div>
  <div class="panel-body">
    <%= comment.comment %>
  </div>
  <% if can?(:destroy, comment) %>
    <div class="panel-footer text-right">
      <%= content_tag :span, raw('<span class="glyphicon glyphicon-remove"></span> Destroy comment'), data: { id: comment.id, href: comment_path(comment) }, class: 'btn btn-xs btn-default destroy-comment' %>
    </div>
  <% end %>
</div>

app/views/comments/_form.erb
<% comment ||= Comment.new(commentable: post) %>
<%= simple_form_for comment, html: { remote: true } do |f| %>
  <%= f.input :commentable_id, as: :hidden %>
  <%= f.input :commentable_type, as: :hidden %>
  <%= f.input :comment, placeholder: 'Comment', label: false %>
  <%= f.button :submit, disabled: cannot?(:create, Comment) %>
<% end %>