config/routes.rb
Rails.application.routes.draw do
  devise_for :user, :skip => [:sessions, :registrations]
  devise_scope :user do
    get "/login" => "devise/sessions#new", as: :new_user_session
    post "/login" => "sessions#create", as: :user_session
    delete "/logout" => "devise/sessions#destroy", as: :destroy_user_session
    get "/sign_up" => "devise/registrations#new", as: :new_user_registration
    post "/sign_up" => "registrations#create", as: :user_registration
  end

  resources :posts
  resources :user_followings, only: [:create, :destroy]
  resources :comments

  get '/users' => 'users#index', as: :users
  get '/users/:id' => 'users#show', as: :user
  root 'users#dashboard'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rekrutacja</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">CJ Group<%= " ( #{current_user.email} )" unless current_user.nil? %></a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Users', users_path %></li>
        <% unless current_user.nil? %>
          <li><%= link_to 'Logout', destroy_session_path(current_user), method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <li><%= link_to 'Log in', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container theme-showcase" role="main">
  <div class="cj-tpl">
    <%= yield %>
  </div>
</div>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
<script>
  App.init();
</script>
</body>
</html>